### ISSUE TITLE
Section Implementation

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft_publication#12]
ToDo:
1. describe gearshifft program usage
2. describe frontend (API for lib implementation)
3. describe backend (gearshifft benchmark system using Boost UTF and C++14)
4. describe timer (where CPU timer, where device timer)

- explain template usage and patterns
- use short listings

Update 1:
5. describe at least one library implementation (including memory checks to prevent out-of-memory kills or context invalidations)
6. cmake project

**Comment by psteinb** [comment]
I think the implementation section should not discuss the program usage. this should go into the benchmark model section. what do you think?

**Comment by tdd11235813** [comment]
I would prefer to write it in the implementation section first, but we can think about it.
Benchmark model sounds more theoretic, but probably it is worthwile to setup the flags in that section and I refer to it.

**Comment by tdd11235813** [comment]
weird, the current version no more contains my PR for implementation, even in the commit history of that file, my commit from 24.11. vanished. I prepare another PR with the missing content. The question is how much else is removed :/

**Comment by psteinb** [comment]
this has been resolved as well by #37. thanks.
