### ISSUE TITLE
Section Benchmark Model

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft_publication#14]
ToDo:
- short intro on FFT, what it does
  - probably mention that common implementation is Cooley-Tukey (but variations exist, like mixed-radix)
- our use case (FFT, iFFT) and why? (Operations done in frequency space) (`x == iFFT( FFT(x) )`)
- transform variants (inplace, outplace), precision types
  - transform variants affect memory usage and runtime

...

**Comment by psteinb** [comment]
thanks for putting this online

**Comment by psteinb** [comment]
started to work on this, see #21

**Comment by psteinb** [comment]
I think we covered this, shall we close this issue?

**Comment by tdd11235813** [comment]
yeah, let's close it :)
