### ISSUE TITLE
fftw fundamentals

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft_publication#30]
while working on the results section, I added subsection on how the fftw API is to be used fundamentally, see [here](https://github.com/mpicbg-scicomp/gearshifft_publication/blob/master/results.tex#L31). 

I am wondering if this should this go before the implementation section?

**Comment by tdd11235813** [comment]
if it is not focused to a specific library, then it can be placed before implementation, otherwise it suits to the implementation section, where specific fft library can be explained, how to use it and how it was integrated in gearshifft .

**Comment by psteinb** [comment]
Yes, I think the design of many (mostly) fftw libraries goes for the 
first-plan-then-run idiom. Which did influence gearshifft in a way. 
Therefor I suggested it.

**Comment by tdd11235813** [comment]
ok, sounds good .. will it be a separate section ? check implementation section where I mapped the typical workflow, probably we can merge some explanations, although at the moment I forgot what I wrote there ;)

**Comment by psteinb** [comment]
I think it's enough to make it a subsection to implementation. Shall I 
send a PR so you can have a look at it?

**Comment by tdd11235813** [comment]
guess it is not needed, so you can work on it as you like and when you have a good feeling, send a PR :)

**Comment by psteinb** [comment]
sure, will do
