### ISSUE TITLE
figures [log]scale

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft_publication#31]
At the moment there are two figures on the same data, where one uses logscale.
Is there a reason that you show the data on two scales, or can we stick to one, preferably with logscale (y log10, x log2 scale). 
For data size I would like to switch back to bytes, when we use logscale there. So it ranges from few bytes to 2^{30} bytes. As a programmer it gives at least for me a better feeling of data size than 2^{-15} MB.

**Comment by psteinb** [comment]
yes, this is on purpose so that the behavior at large input data sizes 
becomes clear in the linear scale plot and the structure at small input 
data volumes in the log plot

**Comment by tdd11235813** [comment]
ok, no prob, the error bars might be more intuitive in the linear scale.
