### ISSUE TITLE
References

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft_publication#41]
I am not sure which references can be removed, thus this issue. I propose:
- FFTW97 (as FFTW05 might be a sufficient entry point)
- remove either dempster2002spread or hurd2010fourier ?
- instead of enumerating deep learning frameworks we could reference to a comparative study like [this one here](https://arxiv.org/abs/1511.06435)
- dongarra2013hpc removable?
- stallman2001using (relates to gcc)

would save 6 references

**Comment by psteinb** [comment]
Are you engineering for space or clearity?
>
>   * FFTW97 (as FFTW05 might be a sufficient entry point)
>
yeah, let's keep FFTW05 only.
>
>   * remove either dempster2002spread or hurd2010fourier ?
>
let's remove dempster2002spread.
>
>   * instead of enumerating deep learning frameworks we could reference
>     to a comparative study like this one here
>     <https://arxiv.org/abs/1511.06435>
>
fine with me.
>
>   * dongarra2013hpc removable?
>
no keep it. it hints to the thought that FFTs are considered a valid 
benchmark of computer systems.
>
>   * stallman2001using (relates to gcc)
>
> would save 6 references
>
I am undecided about this one. I'll leave it up to you. :)

**Comment by tdd11235813** [comment]
k, thanks, I remove them as you proposed ..

**Comment by tdd11235813** [comment]
closed due to #42
