### ISSUE TITLE
front end versus backend

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft_publication#51]
I just read through the implementation section, there is one major issue I see for comprehensibility ... the differentiation between front-end and back-end of gearshifft. 

for me, the front-end of a system is the part that interacts with a user (in our case: reading the CLI, processing/selecting the extents, allocating the signal data, setting up the benchmark cases, executing the benchmarks, comparing the output of the benchmarks with the input), i.e. everything in `src/` and `include/core` . the backend would be how the front-end provided data/parameters is handled (this would be the FFT library clients fftw, cufft, clfft). 

this distinction is quite important for the discussion in `implementation.tex`. the PR that is about to come will take this into account.

**Comment by psteinb** [comment]
any thoughts?

**Comment by tdd11235813** [comment]
oh forgot to consider this, sorry.
For me the front-end is, what the client should see to use the framework to benchmark or to add an FFT library. Besides of program usage (CLI) it also covers the interface for the FFT client code. Back-end handles the benchmark tree generation, result buffering + processing, the application lifetime. So most of core/ is back-end, where fft.hpp would be the interface between back-end and front-end.

**Comment by psteinb** [comment]
ok, then let's stick to this definition.
